//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrdKernalCompat
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="PrdKernalCompat.ZAYGBCSYS_WS_KERNELCOMPAT")]
    public interface ZAYGBCSYS_WS_KERNELCOMPAT
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZAYGBCSYS_WS_KERNELCOMPAT:Zaygbc" +
            "sysRfcsKernelcompatRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PrdKernalCompat.ZaygbcsysRfcsKernelcompatResponse1> ZaygbcsysRfcsKernelcompatAsync(PrdKernalCompat.ZaygbcsysRfcsKernelcompatRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZaygbcsysRfcsKernelcompat
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZaygbcsysKernelstatRf
    {
        
        private string unicodeSytemField;
        
        private string servernameField;
        
        private string hostField;
        
        private string kernelReleaseField;
        
        private string patchLevelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string UnicodeSytem
        {
            get
            {
                return this.unicodeSytemField;
            }
            set
            {
                this.unicodeSytemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Servername
        {
            get
            {
                return this.servernameField;
            }
            set
            {
                this.servernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Host
        {
            get
            {
                return this.hostField;
            }
            set
            {
                this.hostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string KernelRelease
        {
            get
            {
                return this.kernelReleaseField;
            }
            set
            {
                this.kernelReleaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string PatchLevel
        {
            get
            {
                return this.patchLevelField;
            }
            set
            {
                this.patchLevelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZaygbcsysKernelcompatRf
    {
        
        private string[] tSyscheckField;
        
        private ZaygbcsysKernelstatRf sKernelinfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] TSyscheck
        {
            get
            {
                return this.tSyscheckField;
            }
            set
            {
                this.tSyscheckField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ZaygbcsysKernelstatRf SKernelinfo
        {
            get
            {
                return this.sKernelinfoField;
            }
            set
            {
                this.sKernelinfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZaygbcsysRfcsKernelcompatResponse
    {
        
        private ZaygbcsysKernelcompatRf esKernelcompatField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ZaygbcsysKernelcompatRf EsKernelcompat
        {
            get
            {
                return this.esKernelcompatField;
            }
            set
            {
                this.esKernelcompatField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZaygbcsysRfcsKernelcompatRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public PrdKernalCompat.ZaygbcsysRfcsKernelcompat ZaygbcsysRfcsKernelcompat;
        
        public ZaygbcsysRfcsKernelcompatRequest()
        {
        }
        
        public ZaygbcsysRfcsKernelcompatRequest(PrdKernalCompat.ZaygbcsysRfcsKernelcompat ZaygbcsysRfcsKernelcompat)
        {
            this.ZaygbcsysRfcsKernelcompat = ZaygbcsysRfcsKernelcompat;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZaygbcsysRfcsKernelcompatResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public PrdKernalCompat.ZaygbcsysRfcsKernelcompatResponse ZaygbcsysRfcsKernelcompatResponse;
        
        public ZaygbcsysRfcsKernelcompatResponse1()
        {
        }
        
        public ZaygbcsysRfcsKernelcompatResponse1(PrdKernalCompat.ZaygbcsysRfcsKernelcompatResponse ZaygbcsysRfcsKernelcompatResponse)
        {
            this.ZaygbcsysRfcsKernelcompatResponse = ZaygbcsysRfcsKernelcompatResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface ZAYGBCSYS_WS_KERNELCOMPATChannel : PrdKernalCompat.ZAYGBCSYS_WS_KERNELCOMPAT, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class ZAYGBCSYS_WS_KERNELCOMPATClient : System.ServiceModel.ClientBase<PrdKernalCompat.ZAYGBCSYS_WS_KERNELCOMPAT>, PrdKernalCompat.ZAYGBCSYS_WS_KERNELCOMPAT
    {
        
        public ZAYGBCSYS_WS_KERNELCOMPATClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PrdKernalCompat.ZaygbcsysRfcsKernelcompatResponse1> PrdKernalCompat.ZAYGBCSYS_WS_KERNELCOMPAT.ZaygbcsysRfcsKernelcompatAsync(PrdKernalCompat.ZaygbcsysRfcsKernelcompatRequest request)
        {
            return base.Channel.ZaygbcsysRfcsKernelcompatAsync(request);
        }
        
        public System.Threading.Tasks.Task<PrdKernalCompat.ZaygbcsysRfcsKernelcompatResponse1> ZaygbcsysRfcsKernelcompatAsync(PrdKernalCompat.ZaygbcsysRfcsKernelcompat ZaygbcsysRfcsKernelcompat)
        {
            PrdKernalCompat.ZaygbcsysRfcsKernelcompatRequest inValue = new PrdKernalCompat.ZaygbcsysRfcsKernelcompatRequest();
            inValue.ZaygbcsysRfcsKernelcompat = ZaygbcsysRfcsKernelcompat;
            return ((PrdKernalCompat.ZAYGBCSYS_WS_KERNELCOMPAT)(this)).ZaygbcsysRfcsKernelcompatAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
