//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrdSystemFile
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="PrdSystemFile.ZAYGBCSYS_WS_SYSFILE")]
    public interface ZAYGBCSYS_WS_SYSFILE
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZAYGBCSYS_WS_SYSFILE:ZaygbcsysRf" +
            "csSysfileRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PrdSystemFile.ZaygbcsysRfcsSysfileResponse1> ZaygbcsysRfcsSysfileAsync(PrdSystemFile.ZaygbcsysRfcsSysfileRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZaygbcsysRfcsSysfile
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class CcmFsysSingle
    {
        
        private string serverField;
        
        private string fsysnameField;
        
        private int capacityField;
        
        private int freeField;
        
        private int freePercentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Server
        {
            get
            {
                return this.serverField;
            }
            set
            {
                this.serverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Fsysname
        {
            get
            {
                return this.fsysnameField;
            }
            set
            {
                this.fsysnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int Capacity
        {
            get
            {
                return this.capacityField;
            }
            set
            {
                this.capacityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int Free
        {
            get
            {
                return this.freeField;
            }
            set
            {
                this.freeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int FreePercent
        {
            get
            {
                return this.freePercentField;
            }
            set
            {
                this.freePercentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZaygbssysSysfsyRf
    {
        
        private string serverField;
        
        private CcmFsysSingle[] tFsysField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Server
        {
            get
            {
                return this.serverField;
            }
            set
            {
                this.serverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public CcmFsysSingle[] TFsys
        {
            get
            {
                return this.tFsysField;
            }
            set
            {
                this.tFsysField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZaygbcsysRfcsSysfileResponse
    {
        
        private ZaygbssysSysfsyRf[] etFsyInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZaygbssysSysfsyRf[] EtFsyInfo
        {
            get
            {
                return this.etFsyInfoField;
            }
            set
            {
                this.etFsyInfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZaygbcsysRfcsSysfileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public PrdSystemFile.ZaygbcsysRfcsSysfile ZaygbcsysRfcsSysfile;
        
        public ZaygbcsysRfcsSysfileRequest()
        {
        }
        
        public ZaygbcsysRfcsSysfileRequest(PrdSystemFile.ZaygbcsysRfcsSysfile ZaygbcsysRfcsSysfile)
        {
            this.ZaygbcsysRfcsSysfile = ZaygbcsysRfcsSysfile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZaygbcsysRfcsSysfileResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public PrdSystemFile.ZaygbcsysRfcsSysfileResponse ZaygbcsysRfcsSysfileResponse;
        
        public ZaygbcsysRfcsSysfileResponse1()
        {
        }
        
        public ZaygbcsysRfcsSysfileResponse1(PrdSystemFile.ZaygbcsysRfcsSysfileResponse ZaygbcsysRfcsSysfileResponse)
        {
            this.ZaygbcsysRfcsSysfileResponse = ZaygbcsysRfcsSysfileResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface ZAYGBCSYS_WS_SYSFILEChannel : PrdSystemFile.ZAYGBCSYS_WS_SYSFILE, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class ZAYGBCSYS_WS_SYSFILEClient : System.ServiceModel.ClientBase<PrdSystemFile.ZAYGBCSYS_WS_SYSFILE>, PrdSystemFile.ZAYGBCSYS_WS_SYSFILE
    {
        
        public ZAYGBCSYS_WS_SYSFILEClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PrdSystemFile.ZaygbcsysRfcsSysfileResponse1> PrdSystemFile.ZAYGBCSYS_WS_SYSFILE.ZaygbcsysRfcsSysfileAsync(PrdSystemFile.ZaygbcsysRfcsSysfileRequest request)
        {
            return base.Channel.ZaygbcsysRfcsSysfileAsync(request);
        }
        
        public System.Threading.Tasks.Task<PrdSystemFile.ZaygbcsysRfcsSysfileResponse1> ZaygbcsysRfcsSysfileAsync(PrdSystemFile.ZaygbcsysRfcsSysfile ZaygbcsysRfcsSysfile)
        {
            PrdSystemFile.ZaygbcsysRfcsSysfileRequest inValue = new PrdSystemFile.ZaygbcsysRfcsSysfileRequest();
            inValue.ZaygbcsysRfcsSysfile = ZaygbcsysRfcsSysfile;
            return ((PrdSystemFile.ZAYGBCSYS_WS_SYSFILE)(this)).ZaygbcsysRfcsSysfileAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
