//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrdRtmInfo
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="PrdRtmInfo.ZAYGBCSYS_WS_RTMINFO")]
    public interface ZAYGBCSYS_WS_RTMINFO
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZAYGBCSYS_WS_RTMINFO:ZaygbcsysRf" +
            "csRtminfoRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PrdRtmInfo.ZaygbcsysRfcsRtminfoResponse1> ZaygbcsysRfcsRtminfoAsync(PrdRtmInfo.ZaygbcsysRfcsRtminfoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZaygbcsysRfcsRtminfo
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZaygbcsysRstune50Rf
    {
        
        private string bufferField;
        
        private string nameField;
        
        private decimal hitratioField;
        
        private decimal allocSizeField;
        
        private decimal freeSizeField;
        
        private decimal freeSizePField;
        
        private decimal maxObjctsField;
        
        private decimal freeDirField;
        
        private decimal freeDirPField;
        
        private decimal maxSwappedField;
        
        private decimal dbAccessField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Buffer
        {
            get
            {
                return this.bufferField;
            }
            set
            {
                this.bufferField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal Hitratio
        {
            get
            {
                return this.hitratioField;
            }
            set
            {
                this.hitratioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal AllocSize
        {
            get
            {
                return this.allocSizeField;
            }
            set
            {
                this.allocSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal FreeSize
        {
            get
            {
                return this.freeSizeField;
            }
            set
            {
                this.freeSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal FreeSizeP
        {
            get
            {
                return this.freeSizePField;
            }
            set
            {
                this.freeSizePField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal MaxObjcts
        {
            get
            {
                return this.maxObjctsField;
            }
            set
            {
                this.maxObjctsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public decimal FreeDir
        {
            get
            {
                return this.freeDirField;
            }
            set
            {
                this.freeDirField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal FreeDirP
        {
            get
            {
                return this.freeDirPField;
            }
            set
            {
                this.freeDirPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal MaxSwapped
        {
            get
            {
                return this.maxSwappedField;
            }
            set
            {
                this.maxSwappedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal DbAccess
        {
            get
            {
                return this.dbAccessField;
            }
            set
            {
                this.dbAccessField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZaygbcsysRtminfoRf
    {
        
        private string serverField;
        
        private string startupDateField;
        
        private string startupTimeField;
        
        private ZaygbcsysRstune50Rf[] tRtinfoField;
        
        private string errmsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Server
        {
            get
            {
                return this.serverField;
            }
            set
            {
                this.serverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string StartupDate
        {
            get
            {
                return this.startupDateField;
            }
            set
            {
                this.startupDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string StartupTime
        {
            get
            {
                return this.startupTimeField;
            }
            set
            {
                this.startupTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZaygbcsysRstune50Rf[] TRtinfo
        {
            get
            {
                return this.tRtinfoField;
            }
            set
            {
                this.tRtinfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Errmsg
        {
            get
            {
                return this.errmsgField;
            }
            set
            {
                this.errmsgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZaygbcsysRfcsRtminfoResponse
    {
        
        private ZaygbcsysRtminfoRf[] etRtinfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZaygbcsysRtminfoRf[] EtRtinfo
        {
            get
            {
                return this.etRtinfoField;
            }
            set
            {
                this.etRtinfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZaygbcsysRfcsRtminfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public PrdRtmInfo.ZaygbcsysRfcsRtminfo ZaygbcsysRfcsRtminfo;
        
        public ZaygbcsysRfcsRtminfoRequest()
        {
        }
        
        public ZaygbcsysRfcsRtminfoRequest(PrdRtmInfo.ZaygbcsysRfcsRtminfo ZaygbcsysRfcsRtminfo)
        {
            this.ZaygbcsysRfcsRtminfo = ZaygbcsysRfcsRtminfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZaygbcsysRfcsRtminfoResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public PrdRtmInfo.ZaygbcsysRfcsRtminfoResponse ZaygbcsysRfcsRtminfoResponse;
        
        public ZaygbcsysRfcsRtminfoResponse1()
        {
        }
        
        public ZaygbcsysRfcsRtminfoResponse1(PrdRtmInfo.ZaygbcsysRfcsRtminfoResponse ZaygbcsysRfcsRtminfoResponse)
        {
            this.ZaygbcsysRfcsRtminfoResponse = ZaygbcsysRfcsRtminfoResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface ZAYGBCSYS_WS_RTMINFOChannel : PrdRtmInfo.ZAYGBCSYS_WS_RTMINFO, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class ZAYGBCSYS_WS_RTMINFOClient : System.ServiceModel.ClientBase<PrdRtmInfo.ZAYGBCSYS_WS_RTMINFO>, PrdRtmInfo.ZAYGBCSYS_WS_RTMINFO
    {
        
        public ZAYGBCSYS_WS_RTMINFOClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PrdRtmInfo.ZaygbcsysRfcsRtminfoResponse1> PrdRtmInfo.ZAYGBCSYS_WS_RTMINFO.ZaygbcsysRfcsRtminfoAsync(PrdRtmInfo.ZaygbcsysRfcsRtminfoRequest request)
        {
            return base.Channel.ZaygbcsysRfcsRtminfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<PrdRtmInfo.ZaygbcsysRfcsRtminfoResponse1> ZaygbcsysRfcsRtminfoAsync(PrdRtmInfo.ZaygbcsysRfcsRtminfo ZaygbcsysRfcsRtminfo)
        {
            PrdRtmInfo.ZaygbcsysRfcsRtminfoRequest inValue = new PrdRtmInfo.ZaygbcsysRfcsRtminfoRequest();
            inValue.ZaygbcsysRfcsRtminfo = ZaygbcsysRfcsRtminfo;
            return ((PrdRtmInfo.ZAYGBCSYS_WS_RTMINFO)(this)).ZaygbcsysRfcsRtminfoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
